### ISSUE TITLE
I keep getting the same banners

### ISSUE THREAD

**Issue by AnOddName** [emyarod/flattish#29]
I have literally never seen headers #7 - 26

**Comment by emyarod** [comment]
Because of the way "randomness" is achieved through reddit CSS, it isn't actually random. It's explained a bit in the wiki: https://github.com/emyarod/flattish/wiki/Rotating-header-addon

> The random header addon relies on an invisible input form that is tied to the logout button. This input form contains a randomly generated string, and depending on the first character of that string, a different header image will be displayed. There are 36 possible characters (a-z, 0-9), so the 36 characters have to be organized to correspond with the total number of images used.

So while they may not appear for you, it's likely that you'll be able to see different headers if you were on a different account, for example. Not everyone will see the same headers, and it's up to the "randomness" of the string in that input form which is tied to the logout button. It's also why logged out users will see the same header each time

One workaround to this would be to reduce the number of header images I guess.

**Comment by AnOddName** [comment]
Are you sure? I thought the same but I logged in on multiple accounts across multiple devices. My PC, my MacBook, and my IPhone. I thought it was perhaps in my cookies so I cleared them, went to private browsing, same thing. It never gives me any different ones. I asked two of my friends to try, one said he got the cake, which is banner 5, the other said he got the piano keys, which is like banner 32. I'm leaning towards its doing something weird.

**Comment by AnOddName** [comment]
@emyarod I think it might be worth to take another look. http://imgur.com/Tuvl3w5 I asked a couple people to check what it was and one of them even cycled through the same set I get. Maybe there's some kind of seed that gets tied to the logout button that is very common and its just chance that the people I asked got the same ones. I'm unsure but I'll take your word for it

**Comment by emyarod** [comment]
@AnOddName That just means the last character of their logout hash happens to match up with yours. Depending on what character the string ends with, you will get a different header image. I can do a demonstration if you'd like

**Comment by AnOddName** [comment]
Please do. Every account I've tried and people I've spoken with have seen the same ones.

**Comment by emyarod** [comment]
Addressed in https://github.com/emyarod/flattish/commit/5d9a0bfa6ed0f6c0e94465c9ea87076606947c91
